version: '3.8'
services:
  grafana:
    image: grafana/grafana-oss:main
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
volumes:
  grafana_storage: {}
